{
  "swagger": "2.0",
  "info": {
    "version": "1.1",
    "title": "Botsociety Client",
    "description": "Retrieve the content of your chatbot designs automagically.\nThis is the documentation for the version 1.1 of the API.\nPlease feel free to drop questions at info@botsociety.io",
    "contact": {}
  },
  "host": "app.botsociety.io",
  "basePath": "/apisociety/1.1/",
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "userIdHeader": {
      "type": "apiKey",
      "name": "user_id",
      "in": "header"
    },
    "apiKeyHeader": {
      "type": "apiKey",
      "name": "api_key_public",
      "in": "header"
    }
  },
  "security": [
    {
      "userIdHeader": [],
      "apiKeyHeader": []
    }
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/": {
      "get": {
        "description": "Go to your profile page in Botsociety\nhttps://app.botsociety.io/#/account/api\nand generate your API key by clicking on \"Generate new API key\"\nThen add it to your request's header as shown on the right hand side (click \"Auth\" above so see an example).\nYou should expect to receive the following response if everything goes well:\n```\n{\n    \"auth\": true,\n    \"info\": \"You are successfully calling the API. This is just a test API to check your authentication params.\"\n}\n```\nIn case of errors, you should expect to receive the following response:\n```\n{\n    \"auth\": false,\n    \"info\": \"User not auth for the API. Please go to https://app.botsociety.io/#/account/api and generate your API Key. You can find our API documentation here: https://botsociety.docs.apiary.io\"\n}\n```\nThis is just a test API to check your authentication params.",
        "summary": "Auth",
        "operationId": "Auth",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/conversations": {
      "get": {
        "description": "This endpoint will list all of your conversations, together with their name and other details.",
        "summary": "List conversations",
        "operationId": "GetConversations",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ConversationInfo"
              }
            },
            "examples": {
              "application/json": [
                {
                  "_id": "5a72e561f34eeb072c293cfd",
                  "updatedAt": "2018-02-01T10:01:30.137Z",
                  "createdAt": "2018-02-01T10:01:05.751Z",
                  "name": "Test Mockup mockup",
                  "_converted_from": null,
                  "_cloned_from": null,
                  "scenario": null,
                  "selected_variant": "white",
                  "selected_model": "iphone6",
                  "channel": "facebook",
                  "createdByMe": true
                },
                {
                  "_id": "5a72e7f1f34eeb072c293d02",
                  "updatedAt": "2018-02-01T10:12:37.937Z",
                  "createdAt": "2018-02-01T10:12:01.037Z",
                  "name": "Test Bot 2 mockup",
                  "_converted_from": null,
                  "_cloned_from": null,
                  "scenario": null,
                  "selected_variant": "evening",
                  "selected_model": "home",
                  "channel": "googlehome",
                  "createdByMe": true
                }
              ]
            },
            "headers": {}
          }
        }
      }
    },
    "/conversations/{conversation_id}": {
      "get": {
        "description": "This endpoint will list the details of a specific conversation.\nYou have to specify a conversation ID, which you can get from the previous request.\nAlso, you can get the conversation ID by visiting the building mode page, the conversation ID is in the right side.",
        "summary": "Get conversation",
        "operationId": "GetConversation",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "conversation_id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": "ID of the Conversation to retrieve."
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/Conversation"
            },
            "headers": {}
          }
        }
      }
    },
    "/conversations/{conversation_id}/messages/{message_id}": {
      "get": {
        "description": "You can call this endpoint to get the content of a specific message, once you know the unique ID or the progressive ID.\nYou can get the progressive ID by visiting the building mode page (Build button), progressive ID is referenced as \"ID\".",
        "summary": "Get message",
        "operationId": "GetMessage",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "conversation_id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": "ID of the Conversation to retrieve."
          },
          {
            "name": "message_id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": "ID of the Message to retrieve. This can be or the unique ID or the progressive ID."
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/Message"
            },
            "examples": {
              "application/json": {
                "_id": "59b6ada2b674680d16cd7d79",
                "updatedAt": "2017-09-11T15:37:06.775Z",
                "createdAt": "2017-09-11T15:37:06.775Z",
                "_conversation": "59b6abdcb674680d16cd7d74",
                "custom_label": null,
                "type": "text",
                "is_left_side": false,
                "text": "Hello Stefano, how are you today?",
                "next_alternative": null,
                "prev_alternative": null,
                "attachments": [
                  {
                    "choices": [],
                    "labels": []
                  }
                ],
                "next_message": null,
                "is_next_message_linked": false,
                "prev_linked_messages": [],
                "prev_message": "59b6ad99b674680d16cd7d78",
                "show_time": 1500,
                "ssmlText": "<speak>\n  <p><prosody rate=\"slow\">Hello Stefano</prosody>, *pause 1.5s* how are you today?</p>\n</speak>",
                "is_first_message": true,
                "text_with_variables": "Hello ${Name}, how are you today?",
                "progressiveId": 1,
                "intent": "default-intent-0"
              }
            },
            "headers": {}
          }
        }
      }
    },
    "/conversations/{conversation_id}/variables/": {
      "get": {
        "description": "This endpoint will list the variables of a specific conversation. \nVariables may contain one or more values.\nYou have to specify a conversation ID.",
        "summary": "Get variables",
        "operationId": "GetVariables",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "conversation_id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": "ID of the Conversation to retrieve."
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/Variable"
            },
            "examples": {
              "application/json": {
                "Name": {
                  "values": [
                    "Stefano",
                    "Max"
                  ]
                }
              }
            },
            "headers": {}
          }
        }
      }
    }
  },
  "definitions": {
    "ConversationInfo": {
      "title": "ConversationInfo",
      "example": {
        "_id": "5a72e561f34eeb072c293cfd",
        "updatedAt": "2018-02-01T10:01:30.137Z",
        "createdAt": "2018-02-01T10:01:05.751Z",
        "name": "Test Mockup mockup",
        "_converted_from": null,
        "_cloned_from": null,
        "scenario": null,
        "selected_variant": "white",
        "selected_model": "iphone6",
        "channel": "facebook",
        "createdByMe": true
      },
      "type": "object",
      "properties": {
        "_id": {
          "example": "5a72e561f34eeb072c293cfd",
          "type": "string"
        },
        "updatedAt": {
          "example": "2018-02-01T10:01:30.137Z",
          "type": "string"
        },
        "createdAt": {
          "example": "2018-02-01T10:01:05.751Z",
          "type": "string"
        },
        "name": {
          "example": "Test Mockup mockup",
          "type": "string"
        },
        "_converted_from": {
          "type": "string"
        },
        "_cloned_from": {
          "type": "string"
        },
        "scenario": {
          "type": "string"
        },
        "selected_variant": {
          "example": "white",
          "type": "string"
        },
        "selected_model": {
          "example": "iphone6",
          "type": "string"
        },
        "channel": {
          "example": "facebook",
          "type": "string"
        },
        "createdByMe": {
          "example": true,
          "type": "boolean"
        }
      },
      "required": [
        "_id",
        "updatedAt",
        "createdAt",
        "name",
        "selected_variant",
        "selected_model",
        "channel",
        "createdByMe"
      ]
    },
    "Conversation": {
      "title": "Conversation",
      "type": "object",
      "properties": {
        "_id": {
          "type": "string"
        },
        "updatedAt": {
          "type": "string"
        },
        "createdAt": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "_first_message": {
          "type": "string"
        },
        "_converted_from": {
          "type": "string"
        },
        "_cloned_from": {
          "type": "string"
        },
        "scenario": {
          "type": "string"
        },
        "options": {
          "$ref": "#/definitions/Options"
        },
        "menu": {
          "$ref": "#/definitions/Menu"
        },
        "set_welcome": {
          "type": "boolean"
        },
        "ws_page_category": {
          "type": "string"
        },
        "ws_fans": {
          "type": "string"
        },
        "ws_text": {
          "type": "string"
        },
        "rtl": {
          "type": "boolean"
        },
        "selected_variant": {
          "type": "string"
        },
        "selected_model": {
          "type": "string"
        },
        "channel": {
          "type": "string"
        },
        "messages": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Message"
          }
        }
      },
      "required": [
        "_id",
        "updatedAt",
        "createdAt",
        "name",
        "_first_message",
        "options",
        "menu",
        "set_welcome",
        "ws_page_category",
        "ws_fans",
        "ws_text",
        "rtl",
        "selected_variant",
        "selected_model",
        "channel",
        "messages"
      ]
    },
    "Options": {
      "title": "Options",
      "type": "object",
      "properties": {
        "showWelcomeScreen": {
          "type": "boolean"
        },
        "showTypingIndicators": {
          "type": "boolean"
        },
        "showKeyboard": {
          "type": "boolean"
        },
        "backgroundColor": {
          "type": "string"
        }
      },
      "required": [
        "showWelcomeScreen",
        "showTypingIndicators",
        "showKeyboard",
        "backgroundColor"
      ]
    },
    "Menu": {
      "title": "Menu",
      "type": "object",
      "properties": {
        "nodes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Node"
          }
        }
      },
      "required": [
        "nodes"
      ]
    },
    "Node": {
      "title": "Node",
      "type": "object",
      "properties": {
        "messages": {
          "example": [],
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "nodes": {
          "example": [
            {
              "messages": [],
              "nodes": [],
              "title": "Contact us",
              "id": "1a22984b-6b88-2253-9685-ab1521c4548e"
            }
          ],
          "type": "array",
          "items": {
            "$ref": "#/definitions/Node"
          }
        },
        "title": {
          "example": "Help",
          "type": "string"
        },
        "id": {
          "example": "0942ff9f-840d-619d-df0f-7afd5fe99025",
          "type": "string"
        }
      },
      "required": [
        "messages",
        "nodes",
        "title",
        "id"
      ]
    },
    "Message": {
      "title": "Message",
      "type": "object",
      "properties": {
        "_id": {
          "example": "5a72e57af34eeb072c293cff",
          "type": "string"
        },
        "updatedAt": {
          "example": "2018-02-01T10:11:34.560Z",
          "type": "string"
        },
        "createdAt": {
          "example": "2018-02-01T10:11:34.560Z",
          "type": "string"
        },
        "_conversation": {
          "example": "5a72e561f34eeb072c293cfd",
          "type": "string"
        },
        "custom_label": {
          "type": "string"
        },
        "is_left_side": {
          "example": true,
          "type": "boolean"
        },
        "text": {
          "example": "I'm a bot",
          "type": "string"
        },
        "type": {
          "example": "text",
          "type": "string"
        },
        "next_alternative": {
          "type": "string"
        },
        "prev_alternative": {
          "type": "string"
        },
        "attachments": {
          "example": [
            {
              "choices": [],
              "labels": [],
              "size": "horizontal"
            }
          ],
          "type": "array",
          "items": {
            "$ref": "#/definitions/Attachment"
          }
        },
        "next_message": {
          "example": "5a72e7d8f34eeb072c293d00",
          "type": "string"
        },
        "is_next_message_linked": {
          "example": false,
          "type": "boolean"
        },
        "prev_linked_messages": {
          "example": [],
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "prev_message": {
          "type": "string"
        },
        "show_time": {
          "example": 1500,
          "type": "integer",
          "format": "int32"
        },
        "is_first_message": {
          "example": true,
          "type": "boolean"
        },
        "text_with_variables": {
          "example": "I'm a ${whoami}",
          "type": "string"
        },
        "progressiveId": {
          "example": 1,
          "type": "integer",
          "format": "int32"
        },
        "intent": {
          "example": "default-intent-0",
          "type": "string"
        }
      },
      "required": [
        "_id",
        "updatedAt",
        "createdAt",
        "_conversation",
        "is_left_side",
        "text",
        "type",
        "attachments",
        "next_message",
        "is_next_message_linked",
        "prev_linked_messages",
        "show_time",
        "is_first_message",
        "text_with_variables",
        "progressiveId",
        "intent"
      ]
    },
    "Attachment": {
      "title": "Attachment",
      "example": {
        "choices": [],
        "labels": [],
        "size": "horizontal"
      },
      "type": "object",
      "properties": {
        "choices": {
          "example": [],
          "type": "array",
          "items": {
            "type": "object"
          }
        },
        "labels": {
          "example": [],
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "size": {
          "example": "horizontal",
          "type": "string"
        }
      },
      "required": [
        "choices",
        "labels",
        "size"
      ]
    },
    "Variable": {
      "title": "Variable",
      "example": {
        "Name": {
          "values": [
            "Stefano",
            "Max"
          ]
        }
      },
      "type": "object",
      "properties": {
        "Name": {
          "$ref": "#/definitions/Name"
        }
      },
      "required": [
        "Name"
      ]
    },
    "Name": {
      "title": "Name",
      "type": "object",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "values"
      ]
    }
  },
  "tags": []
}