{
    "swagger": "2.0",
    "info": {
      "version": "1.0",
      "title": "Botsociety API",
      "description": "Retrieve the content of your chatbot designs automagically.\nThis is the documentation for the version 1.1 of the API.\nPlease feel free to drop questions at info@botsociety.io",
      "contact": {}
    },
    "host": "app.botsociety.io",
    "basePath": "/apisociety/1.1/",
    "schemes": [
      "https"
    ],
    "consumes": [
      "application/json"
    ],
    "produces": [
      "application/json"
    ],
    "paths": {
      "/": {
        "get": {
          "description": "Go to your profile page in Botsociety\nhttps://app.botsociety.io/#/account/api\nand generate your API key by clicking on \"Generate new API key\"\nThen add it to your request's header as shown on the right hand side (click \"Auth\" above so see an example).\nYou should expect to receive the following response if everything goes well:\n```\n{\n    \"auth\": true,\n    \"info\": \"You are successfully calling the API. This is just a test API to check your authentication params.\"\n}\n```\nIn case of errors, you should expect to receive the following response:\n```\n{\n    \"auth\": false,\n    \"info\": \"User not auth for the API. Please go to https://app.botsociety.io/#/account/api and generate your API Key. You can find our API documentation here: https://botsociety.docs.apiary.io\"\n}\n```\nThis is just a test API to check your authentication params.",
          "summary": "Auth",
          "operationId": "UnnammedEndpointGet",
          "deprecated": false,
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "Content-Type",
              "in": "header",
              "required": true,
              "type": "string",
              "description": ""
            },
            {
              "name": "user_id",
              "in": "header",
              "required": true,
              "type": "string",
              "description": ""
            },
            {
              "name": "api_key_public",
              "in": "header",
              "required": true,
              "type": "string",
              "description": ""
            }
          ],
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          }
        }
      },
      "/conversations": {
        "get": {
          "description": "This endpoint will list all of your conversations, together with their name and other details.",
          "summary": "List conversations",
          "operationId": "ConversationsGet",
          "deprecated": false,
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "Content-Type",
              "in": "header",
              "required": true,
              "type": "string",
              "description": ""
            }
          ],
          "responses": {
            "200": {
              "description": "",
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/Listconversationsresponse"
                }
              },
              "examples": {
                "application/json": [
                  {
                    "_id": "5a72e561f34eeb072c293cfd",
                    "updatedAt": "2018-02-01T10:01:30.137Z",
                    "createdAt": "2018-02-01T10:01:05.751Z",
                    "name": "Test Mockup mockup",
                    "_converted_from": null,
                    "_cloned_from": null,
                    "scenario": null,
                    "selected_variant": "white",
                    "selected_model": "iphone6",
                    "channel": "facebook",
                    "createdByMe": true
                  },
                  {
                    "_id": "5a72e7f1f34eeb072c293d02",
                    "updatedAt": "2018-02-01T10:12:37.937Z",
                    "createdAt": "2018-02-01T10:12:01.037Z",
                    "name": "Test Bot 2 mockup",
                    "_converted_from": null,
                    "_cloned_from": null,
                    "scenario": null,
                    "selected_variant": "evening",
                    "selected_model": "home",
                    "channel": "googlehome",
                    "createdByMe": true
                  }
                ]
              },
              "headers": {}
            }
          }
        }
      },
      "/conversations/{conversation_id}": {
        "get": {
          "description": "This endpoint will list the details of a specific conversation.\nYou have to specify a conversation ID, which you can get from the previous request.\nAlso, you can get the conversation ID by visiting the building mode page, the conversation ID is in the right side.",
          "summary": "Get conversation",
          "operationId": "ConversationsByConversationIdGet",
          "deprecated": false,
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "conversation_id",
              "in": "path",
              "required": true,
              "type": "string",
              "description": "ID of the Conversation to retrieve."
            },
            {
              "name": "Content-Type",
              "in": "header",
              "required": true,
              "type": "string",
              "description": ""
            },
            {
              "name": "user_id",
              "in": "header",
              "required": true,
              "type": "string",
              "description": ""
            },
            {
              "name": "api_key_public",
              "in": "header",
              "required": true,
              "type": "string",
              "description": ""
            }
          ],
          "responses": {
            "200": {
              "description": "",
              "schema": {
                "$ref": "#/definitions/Getconversationresponse"
              },
              "headers": {}
            }
          }
        }
      },
      "/conversations/{conversation_id}/messages/{message_id}": {
        "get": {
          "description": "You can call this endpoint to get the content of a specific message, once you know the unique ID or the progressive ID.\nYou can get the progressive ID by visiting the building mode page (Build button), progressive ID is referenced as \"ID\".",
          "summary": "Get message",
          "operationId": "ConversationsMessagesByConversationIdAndMessageIdGet",
          "deprecated": false,
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "conversation_id",
              "in": "path",
              "required": true,
              "type": "string",
              "description": "ID of the Conversation to retrieve."
            },
            {
              "name": "message_id",
              "in": "path",
              "required": true,
              "type": "string",
              "description": "ID of the Message to retrieve. This can be or the unique ID or the progressive ID."
            },
            {
              "name": "Content-Type",
              "in": "header",
              "required": true,
              "type": "string",
              "description": ""
            },
            {
              "name": "user_id",
              "in": "header",
              "required": true,
              "type": "string",
              "description": ""
            },
            {
              "name": "api_key_public",
              "in": "header",
              "required": true,
              "type": "string",
              "description": ""
            }
          ],
          "responses": {
            "200": {
              "description": "",
              "schema": {
                "$ref": "#/definitions/Getmessageresponse"
              },
              "examples": {
                "application/json": {
                  "_id": "59b6ada2b674680d16cd7d79",
                  "updatedAt": "2017-09-11T15:37:06.775Z",
                  "createdAt": "2017-09-11T15:37:06.775Z",
                  "_conversation": "59b6abdcb674680d16cd7d74",
                  "custom_label": null,
                  "type": "text",
                  "is_left_side": false,
                  "text": "Hello Stefano, how are you today?",
                  "next_alternative": null,
                  "prev_alternative": null,
                  "attachments": [
                    {
                      "choices": [],
                      "labels": []
                    }
                  ],
                  "next_message": null,
                  "is_next_message_linked": false,
                  "prev_linked_messages": [],
                  "prev_message": "59b6ad99b674680d16cd7d78",
                  "show_time": 1500,
                  "ssmlText": "<speak>\n  <p><prosody rate=\"slow\">Hello Stefano</prosody>, *pause 1.5s* how are you today?</p>\n</speak>",
                  "is_first_message": true,
                  "text_with_variables": "Hello ${Name}, how are you today?",
                  "progressiveId": 1,
                  "intent": "default-intent-0"
                }
              },
              "headers": {}
            }
          }
        }
      },
      "/conversations/{conversation_id}/variables/": {
        "get": {
          "description": "This endpoint will list the variables of a specific conversation. \nVariables may contain one or more values.\nYou have to specify a conversation ID.",
          "summary": "Get variables",
          "operationId": "ConversationsVariablesByConversationIdGet",
          "deprecated": false,
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "conversation_id",
              "in": "path",
              "required": true,
              "type": "string",
              "description": "ID of the Conversation to retrieve."
            },
            {
              "name": "Content-Type",
              "in": "header",
              "required": true,
              "type": "string",
              "description": ""
            },
            {
              "name": "user_id",
              "in": "header",
              "required": true,
              "type": "string",
              "description": ""
            },
            {
              "name": "api_key_public",
              "in": "header",
              "required": true,
              "type": "string",
              "description": ""
            }
          ],
          "responses": {
            "200": {
              "description": "",
              "schema": {
                "$ref": "#/definitions/Getvariablesresponse"
              },
              "examples": {
                "application/json": {
                  "Name": {
                    "values": [
                      "Stefano",
                      "Max"
                    ]
                  }
                }
              },
              "headers": {}
            }
          }
        }
      },
      "/messages/{message_id}": {
        "get": {
          "description": "You can call this endpoint to get the content of a specific message, once you know the message id.",
          "summary": "DEPRECATED - Get message",
          "operationId": "MessagesByMessageIdGet",
          "deprecated": false,
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "message_id",
              "in": "path",
              "required": true,
              "type": "string",
              "description": "ID of the Message to retrieve. This must be unique ID."
            },
            {
              "name": "Content-Type",
              "in": "header",
              "required": true,
              "type": "string",
              "description": ""
            },
            {
              "name": "user_id",
              "in": "header",
              "required": true,
              "type": "string",
              "description": ""
            },
            {
              "name": "api_key_public",
              "in": "header",
              "required": true,
              "type": "string",
              "description": ""
            }
          ],
          "responses": {
            "200": {
              "description": "",
              "schema": {
                "$ref": "#/definitions/DEPRECATED-Getmessageresponse"
              },
              "examples": {
                "application/json": {
                  "_id": "59b6ada2b674680d16cd7d79",
                  "updatedAt": "2017-09-11T15:37:06.775Z",
                  "createdAt": "2017-09-11T15:37:06.775Z",
                  "type": "text",
                  "side": false,
                  "text": "Hello Stefano, how are you today?",
                  "text_with_variables": "Hello ${Name}, how are you today?",
                  "_conversation": "59b6abdcb674680d16cd7d74",
                  "next_alternative": null,
                  "prev_alternative": null,
                  "attachments": [
                    {
                      "choices": [],
                      "labels": []
                    }
                  ],
                  "next_message": null,
                  "is_next_message_linked": false,
                  "prev_linked_messages": [],
                  "prev_message": "59b6ad99b674680d16cd7d78",
                  "show_time": 1500
                }
              },
              "headers": {}
            }
          }
        }
      }
    },
    "definitions": {
      "Listconversationsresponse": {
        "title": "Listconversationsresponse",
        "example": {
          "_id": "5a72e561f34eeb072c293cfd",
          "updatedAt": "2018-02-01T10:01:30.137Z",
          "createdAt": "2018-02-01T10:01:05.751Z",
          "name": "Test Mockup mockup",
          "_converted_from": null,
          "_cloned_from": null,
          "scenario": null,
          "selected_variant": "white",
          "selected_model": "iphone6",
          "channel": "facebook",
          "createdByMe": true
        },
        "type": "object",
        "properties": {
          "_id": {
            "example": "5a72e561f34eeb072c293cfd",
            "type": "string"
          },
          "updatedAt": {
            "example": "2018-02-01T10:01:30.137Z",
            "type": "string"
          },
          "createdAt": {
            "example": "2018-02-01T10:01:05.751Z",
            "type": "string"
          },
          "name": {
            "example": "Test Mockup mockup",
            "type": "string"
          },
          "_converted_from": {
            "type": "string"
          },
          "_cloned_from": {
            "type": "string"
          },
          "scenario": {
            "type": "string"
          },
          "selected_variant": {
            "example": "white",
            "type": "string"
          },
          "selected_model": {
            "example": "iphone6",
            "type": "string"
          },
          "channel": {
            "example": "facebook",
            "type": "string"
          },
          "createdByMe": {
            "example": true,
            "type": "boolean"
          }
        },
        "required": [
          "_id",
          "updatedAt",
          "createdAt",
          "name",
          "selected_variant",
          "selected_model",
          "channel",
          "createdByMe"
        ]
      },
     
      "Options": {
        "title": "Options",
        "type": "object",
        "properties": {
          "showWelcomeScreen": {
            "type": "boolean"
          },
          "showTypingIndicators": {
            "type": "boolean"
          },
          "showKeyboard": {
            "type": "boolean"
          },
          "backgroundColor": {
            "type": "string"
          }
        },
        "required": [
          "showWelcomeScreen",
          "showTypingIndicators",
          "showKeyboard",
          "backgroundColor"
        ]
      },
      "Menu": {
        "title": "Menu",
        "type": "object",
        "properties": {
          "nodes": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/Node"
            }
          }
        },
        "required": [
          "nodes"
        ]
      },
      "Node": {
        "title": "Node",
        "type": "object",
        "properties": {
          "messages": {
            "example": [],
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "nodes": {
            "example": [
              {
                "messages": [],
                "nodes": [],
                "title": "Contact us",
                "id": "1a22984b-6b88-2253-9685-ab1521c4548e"
              }
            ],
            "type": "array",
            "items": {
              "$ref": "#/definitions/Node1"
            }
          },
          "title": {
            "example": "Help",
            "type": "string"
          },
          "id": {
            "example": "0942ff9f-840d-619d-df0f-7afd5fe99025",
            "type": "string"
          }
        },
        "required": [
          "messages",
          "nodes",
          "title",
          "id"
        ]
      },
      "Node1": {
        "title": "Node1",
        "example": {
          "messages": [],
          "nodes": [],
          "title": "Contact us",
          "id": "1a22984b-6b88-2253-9685-ab1521c4548e"
        },
        "type": "object",
        "properties": {
          "messages": {
            "example": [],
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "nodes": {
            "example": [],
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "title": {
            "example": "Contact us",
            "type": "string"
          },
          "id": {
            "example": "1a22984b-6b88-2253-9685-ab1521c4548e",
            "type": "string"
          }
        },
        "required": [
          "messages",
          "nodes",
          "title",
          "id"
        ]
      },
      "Message": {
        "title": "Message",
        "type": "object",
        "properties": {
          "_id": {
            "example": "5a72e57af34eeb072c293cff",
            "type": "string"
          },
          "updatedAt": {
            "example": "2018-02-01T10:11:34.560Z",
            "type": "string"
          },
          "createdAt": {
            "example": "2018-02-01T10:11:34.560Z",
            "type": "string"
          },
          "_conversation": {
            "example": "5a72e561f34eeb072c293cfd",
            "type": "string"
          },
          "custom_label": {
            "type": "string"
          },
          "is_left_side": {
            "example": true,
            "type": "boolean"
          },
          "text": {
            "example": "I'm a bot",
            "type": "string"
          },
          "type": {
            "example": "text",
            "type": "string"
          },
          "next_alternative": {
            "type": "string"
          },
          "prev_alternative": {
            "type": "string"
          },
          "attachments": {
            "example": [
              {
                "choices": [],
                "labels": [],
                "size": "horizontal"
              }
            ],
            "type": "array",
            "items": {
              "$ref": "#/definitions/Attachment"
            }
          },
          "next_message": {
            "example": "5a72e7d8f34eeb072c293d00",
            "type": "string"
          },
          "is_next_message_linked": {
            "example": false,
            "type": "boolean"
          },
          "prev_linked_messages": {
            "example": [],
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "prev_message": {
            "type": "string"
          },
          "show_time": {
            "example": 1500,
            "type": "integer",
            "format": "int32"
          },
          "is_first_message": {
            "example": true,
            "type": "boolean"
          },
          "text_with_variables": {
            "example": "I'm a ${whoami}",
            "type": "string"
          },
          "progressiveId": {
            "example": 1,
            "type": "integer",
            "format": "int32"
          },
          "intent": {
            "example": "default-intent-0",
            "type": "string"
          }
        },
        "required": [
          "_id",
          "updatedAt",
          "createdAt",
          "_conversation",
          "is_left_side",
          "text",
          "type",
          "attachments",
          "next_message",
          "is_next_message_linked",
          "prev_linked_messages",
          "show_time",
          "is_first_message",
          "text_with_variables",
          "progressiveId",
          "intent"
        ]
      },
      "Attachment": {
        "title": "Attachment",
        "example": {
          "choices": [],
          "labels": [],
          "size": "horizontal"
        },
        "type": "object",
        "properties": {
          "choices": {
            "example": [],
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "labels": {
            "example": [],
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "size": {
            "example": "horizontal",
            "type": "string"
          }
        },
        "required": [
          "choices",
          "labels",
          "size"
        ]
      },
      "Getmessageresponse": {
        "title": "Getmessageresponse",
        "example": {
          "_id": "59b6ada2b674680d16cd7d79",
          "updatedAt": "2017-09-11T15:37:06.775Z",
          "createdAt": "2017-09-11T15:37:06.775Z",
          "_conversation": "59b6abdcb674680d16cd7d74",
          "custom_label": null,
          "type": "text",
          "is_left_side": false,
          "text": "Hello Stefano, how are you today?",
          "next_alternative": null,
          "prev_alternative": null,
          "attachments": [
            {
              "choices": [],
              "labels": []
            }
          ],
          "next_message": null,
          "is_next_message_linked": false,
          "prev_linked_messages": [],
          "prev_message": "59b6ad99b674680d16cd7d78",
          "show_time": 1500,
          "ssmlText": "<speak>\n  <p><prosody rate=\"slow\">Hello Stefano</prosody>, *pause 1.5s* how are you today?</p>\n</speak>",
          "is_first_message": true,
          "text_with_variables": "Hello ${Name}, how are you today?",
          "progressiveId": 1,
          "intent": "default-intent-0"
        },
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          },
          "_conversation": {
            "type": "string"
          },
          "custom_label": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "is_left_side": {
            "type": "boolean"
          },
          "text": {
            "type": "string"
          },
          "next_alternative": {
            "type": "string"
          },
          "prev_alternative": {
            "type": "string"
          },
          "attachments": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/Attachment1"
            }
          },
          "next_message": {
            "type": "string"
          },
          "is_next_message_linked": {
            "type": "boolean"
          },
          "prev_linked_messages": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "prev_message": {
            "type": "string"
          },
          "show_time": {
            "type": "integer",
            "format": "int32"
          },
          "ssmlText": {
            "type": "string"
          },
          "is_first_message": {
            "type": "boolean"
          },
          "text_with_variables": {
            "type": "string"
          },
          "progressiveId": {
            "type": "integer",
            "format": "int32"
          },
          "intent": {
            "type": "string"
          }
        },
        "required": [
          "_id",
          "updatedAt",
          "createdAt",
          "_conversation",
          "type",
          "is_left_side",
          "text",
          "attachments",
          "is_next_message_linked",
          "prev_linked_messages",
          "prev_message",
          "show_time",
          "ssmlText",
          "is_first_message",
          "text_with_variables",
          "progressiveId",
          "intent"
        ]
      },
      "Attachment1": {
        "title": "Attachment1",
        "type": "object",
        "properties": {
          "choices": {
            "example": [],
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "labels": {
            "example": [],
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "choices",
          "labels"
        ]
      },
      "Getvariablesresponse": {
        "title": "Getvariablesresponse",
        "example": {
          "Name": {
            "values": [
              "Stefano",
              "Max"
            ]
          }
        },
        "type": "object",
        "properties": {
          "Name": {
            "$ref": "#/definitions/Name"
          }
        },
        "required": [
          "Name"
        ]
      },
      "Name": {
        "title": "Name",
        "type": "object",
        "properties": {
          "values": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "values"
        ]
      },
      "DEPRECATED-Getmessageresponse": {
        "title": "DEPRECATED-Getmessageresponse",
        "example": {
          "_id": "59b6ada2b674680d16cd7d79",
          "updatedAt": "2017-09-11T15:37:06.775Z",
          "createdAt": "2017-09-11T15:37:06.775Z",
          "type": "text",
          "side": false,
          "text": "Hello Stefano, how are you today?",
          "text_with_variables": "Hello ${Name}, how are you today?",
          "_conversation": "59b6abdcb674680d16cd7d74",
          "next_alternative": null,
          "prev_alternative": null,
          "attachments": [
            {
              "choices": [],
              "labels": []
            }
          ],
          "next_message": null,
          "is_next_message_linked": false,
          "prev_linked_messages": [],
          "prev_message": "59b6ad99b674680d16cd7d78",
          "show_time": 1500
        },
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "side": {
            "type": "boolean"
          },
          "text": {
            "type": "string"
          },
          "text_with_variables": {
            "type": "string"
          },
          "_conversation": {
            "type": "string"
          },
          "next_alternative": {
            "type": "string"
          },
          "prev_alternative": {
            "type": "string"
          },
          "attachments": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/Attachment1"
            }
          },
          "next_message": {
            "type": "string"
          },
          "is_next_message_linked": {
            "type": "boolean"
          },
          "prev_linked_messages": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "prev_message": {
            "type": "string"
          },
          "show_time": {
            "type": "integer",
            "format": "int32"
          }
        },
        "required": [
          "_id",
          "updatedAt",
          "createdAt",
          "type",
          "side",
          "text",
          "text_with_variables",
          "_conversation",
          "attachments",
          "is_next_message_linked",
          "prev_linked_messages",
          "prev_message",
          "show_time"
        ]
      }
    },
    "tags": []
  }